Key2Home/Models/Campaign.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Key2Home.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string OwnerShip { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}

Key2Home/Controllers/CampaignController.cs
using Key2Home.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Key2Home.Controllers
{
    public class CampaignController : Controller
    {
        KeyToHomeEntities db = new KeyToHomeEntities();
        // GET: Campaign
        public ActionResult Index()
        {
            try
            {           
                
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View();
        }
    
        [HttpGet]
        public ActionResult CreateCampaign()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult CreateCampaign(Campaign EntityCampaign)
        {
            EntityCampaign.CreatedDate = DateTime.Now;
            EntityCampaign.IsActive = true;
            db.Campaigns.Add(EntityCampaign);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditCampaign(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }            
            var CampaignData = db.Campaigns.Where(m => m.Id == id).FirstOrDefault();
            ViewBag.CampaignId = CampaignData.Id;            
            if (CampaignData == null)
            {
                return HttpNotFound();
            }
            return View(CampaignData);
        }

        [HttpPost]
        public ActionResult EditCampaign(Campaign EntityCampaign)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(EntityCampaign).State = EntityState.Modified;
                    db.SaveChanges();
                    ModelState.Clear();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public JsonResult DeleteCampaign(int? id)
        {
            if (id != null)
            {
                var DelCampaign = db.Campaigns.Single(s => s.Id == id);              
                DelCampaign.IsActive = false;
            }
            db.SaveChanges();
            return Json("Success", JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetAllCampaign()
        {
            try
            {
                var getAllCampaign = db.Campaigns.Where(m => m.IsActive == true).OrderByDescending(m => m.CreatedDate).ToList();
                //var getAllUsers = db.users.OrderBy(x => x.CreatedOn).ToList();
                // var getAllCampaign = db.Campaigns.ToList();
                // var getAllUsers = db.users.ToList();
                if (getAllCampaign.Count() > 0)
                {
                    ViewBag.RecordExists = "true";
                }
                return Json(getAllCampaign, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

    }
}

Key2Home/Views/Campaign/CreateCampaign.cshtml
@model Key2Home.Models.Campaign
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("CreateCampaign", "Campaign", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="main">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 p-r-0 title-margin-right">
                    <div class="page-header">
                        <div class="page-title">
                            <h1>Create Campaign</h1>
                        </div>
                    </div>
                </div>
                <!-- /# column -->
                <div class="col-lg-4 p-l-0 title-margin-left">
                    <div class="page-header">
                        <div class="page-title">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3">
                </div>
                <div class="col-lg-6">
                    <form class="card form-horizontal">
                        <div class="form-group">
                            <label>Name</label>
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Internal Name" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            @Html.TextBoxFor(model => model.Description, new { @class = "form-control", @placeholder = "Subject" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label>Status</label>
                            <div>
                                <input type="hidden" value=""><label class="radio-inline">  </label>
                                @Html.RadioButton("Owner-type", "Private", new { @style = "margin-left:10%", @id = "Private" }) <label>Private</label>
                                @Html.RadioButton("Owner-type", "Office", new { @id = "Office" }) <label>Office</label>
                                @Html.Hidden("OwnerShip")
                                <div class="error-block"></div>
                                <p></p><small class="help-block">Select "Office" if you would like to share this template with your team.</small>
                            </div>
                        </div>
                        <div class="col-lg-6">                        
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" id="btn_CreateCampaign" value="Save">
                                <input type="submit" value="Cancel" class="btn btn-default">
                            </div>                       
                        </div>               
                    </form>
                </div>
                <div class="col-lg-3">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3">
                </div>
                <div class="col-lg-6">
                    <h3 style="text-align: center">When this campaign is assigned</h3>
                </div>
                <div class="col-lg-3">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3">
                </div>
                <div class="col-lg-6">
                    <form class="card form-horizontal">
                        <h4>Send an email</h4>
                        <div class="form-group">
                            <label>Description</label>
                            <input class="form-control" placeholder="Subject" type="text">
                        </div>
                        <div class="form-group">
                            <label>Body</label>
                            <div class="input-group input-group-default">
                                <span class="input-group-btn"><button class="btn btn-primary"><i class="fa fa-edit"></i></button></span>
                                <input placeholder="Type Something" class="form-control" type="text">
                            </div>
                            <small class="help-block">When this email is delivered, the user's email signature, your company's address, and an unsubscribe link will be automatically appended to help reduce spam reports and improve email quality.</small>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Done" class="btn btn-primary">
                            <input type="submit" value="Cancel" class="btn btn-default">
                        </div>
                    </form>
                </div>
                <div class="col-lg-3">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3">
                </div>
              
                <div class="col-lg-3">
                </div>
            </div>
        </div>
    </div>
}
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
        $("input:radio").click(function () {
            if ($('input[name=Owner-type]:checked').val() == "Private") {
                var OwnerShip = $('#Private').val();
                $('#OwnerShip').val(OwnerShip);
                alert(OwnerShip);
                $('#Office').prop("checked", false);             
            }
            if ($('input[name=Owner-type]:checked').val() == "Office") {
                var OwnerShip = $('#Office').val();
                $('#OwnerShip').val(OwnerShip);
                alert(OwnerShip);
                $('#Private').prop("checked", false);             
            }    
            });
        });
    </script>
    }

Key2Home/Views/Campaign/EditCampaign.cshtml
@model Key2Home.Models.Campaign
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("EditCampaign", "Campaign", FormMethod.Post, new { encType = "multipart/form-data", @class = "form-horizontal" }))
{
    @Html.HiddenFor(model => model.CreatedDate)
    <div class="main">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 p-r-0 title-margin-right">
                    <div class="page-header">
                        <div class="page-title">
                            <h1>Edit Campaign</h1>
                        </div>
                    </div>
                </div>
                <!-- /# column -->
                <div class="col-lg-4 p-l-0 title-margin-left">
                    <div class="page-header">
                        <div class="page-title">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3">
                </div>
                <div class="col-lg-6">
                    <form class="card form-horizontal">
                        <div class="form-group">
                            <label>Name</label>
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Internal Name" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            @Html.TextBoxFor(model => model.Description, new { @class = "form-control", @placeholder = "Subject" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label>Status</label>
                            <div>
                                <input type="hidden" value=""><label class="radio-inline">  </label>
                                @Html.RadioButton("Owner-type", "Private", new { @style = "margin-left:10%", @id = "Private" }) <label>Private</label>
                                @Html.RadioButton("Owner-type", "Office", new { @id = "Office" }) <label>Office</label>
                                @Html.Hidden("OwnerShip")
                                <div class="error-block"></div>
                                <p></p><small class="help-block">Select "Office" if you would like to share this template with your team.</small>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" id="btn_CreateCampaign" value="Save">
                                <input type="submit" value="Cancel" class="btn btn-default">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-3">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3">
                </div>
                <div class="col-lg-6">
                    <h3 style="text-align: center">When this campaign is assigned</h3>
                </div>
                <div class="col-lg-3">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3">
                </div>
                <div class="col-lg-6">
                    <form class="card form-horizontal">
                        <h4>Send an email</h4>
                        <div class="form-group">
                            <label>Description</label>
                            <input class="form-control" placeholder="Subject" type="text">
                        </div>
                        <div class="form-group">
                            <label>Body</label>
                            <div class="input-group input-group-default">
                                <span class="input-group-btn"><button class="btn btn-primary"><i class="fa fa-edit"></i></button></span>
                                <input placeholder="Type Something" class="form-control" type="text">
                            </div>
                            <small class="help-block">When this email is delivered, the user's email signature, your company's address, and an unsubscribe link will be automatically appended to help reduce spam reports and improve email quality.</small>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Done" class="btn btn-primary">
                            <input type="submit" value="Cancel" class="btn btn-default">
                        </div>
                    </form>
                </div>
                <div class="col-lg-3">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3">
                </div>
                <div class="col-lg-6">
                    <form class="card form-horizontal">
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-primary">
                            <input type="submit" value="Cancel" class="btn btn-default">
                        </div>
                    </form>
                </div>
                <div class="col-lg-3">
                </div>
            </div>
        </div>
    </div>
}
    @section scripts{
        <script type="text/javascript">
            $(document).ready(function () {
                if ($("#OwnerShip").val() == 'Private') {
                    $('#Private').prop("checked", true);
                }
                else if ($("#OwnerShip").val() == 'Office') {
                    $('#Office').prop("checked", true);
                }
                $("input:radio").click(function () {
                    if ($('input[name=Owner-type]:checked').val() == "Private") {
                        var OwnerShip = $('#Private').val();
                        $('#OwnerShip').val(OwnerShip);
                        //  alert($('#roles').val());
                        // values.push(this.value);
                        $('#Office').prop("checked", false);
                    }
                    if ($('input[name=Owner-type]:checked').val() == "Office") {
                        var OwnerShip = $('#Office').val();
                        $('#OwnerShip').val(OwnerShip);
                        $('#Private').prop("checked", false);
                    }
                });
            });
        </script>
    }

Key2Home/Views/Campaign/Index.cshtml
@model Key2Home.Models.Campaign
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .color_div {
        color: #269e56 !important;
    }
</style>
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog" style="width: 500px;height: 108px;position: absolute;top: 20%;left: 50%;margin-top: -48px; margin-left: -239px;padding: 15px;">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Delete</h3>
            </div>
            <div class="modal-body">
                <p>DO YOU WANT TO DELETE SELECTED USERS?</p>
            </div>
            <div class="modal-footer">
                <a href="#" id="btnYes" class="btn btn-primary">Yes</a>
                <a href="#" id="btnNo" data-dismiss="modal" aria-hidden="true" class="btn btn-primary">No</a>
            </div>
        </div>
    </div>
</div>
<div class="main">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8 p-r-0 title-margin-right">
                <div class="page-header">
                    <div class="page-title">
                        <h1>
                            Campaign
                        </h1>
                    </div>
                </div>
            </div>
            <!-- /# column -->
            <div class="col-lg-4 p-l-0 title-margin-left">
                <div class="page-header">
                    <div class="page-title">
                    </div>
                </div>
            </div>
            <!-- /# column -->
        </div>
        <div id="main-content">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card alert">
                        <div class="card-header">
                            <h4>Campaign</h4>
                            <div class="card-header-right-icon">
                                <a href="@Url.Action("CreateCampaign","Campaign")" class="btn btn-primary btn-xs btn-flat"><i class="ti-plus"></i> Add New</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-hover" id="Campaigns">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Description</th>
                                            <th>Owner</th>
                                            <th>Created On</th>
                                            <th>Edit</th>
                                            <th>Delete</th>
                                        </tr>
                                    </thead>
                                </table>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /# card -->
            <!-- /# row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer">
                        <p>This dashboard was generated on <span id="date-time"></span> <a href="#" class="page-refresh">Keys2Home</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id='myModal' class='modal'>
    <div class="modal-dialog" style="width: 500px;height: 108px;position: absolute;top: 20%;left: 50%;margin-top: -48px; margin-left: -239px;padding: 15px;">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>
@section scripts
     {
    @*<script type="text/javascript" src="http://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>*@
    <script type="text/javascript" src="https://cdn.datatables.net/fixedcolumns/3.2.3/js/dataTables.fixedColumns.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/9dcbecd42ad/integration/jqueryui/dataTables.jqueryui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/plug-ins/9dcbecd42ad/integration/jqueryui/dataTables.jqueryui.css">
    <script>
        function convert(str) {
            var date = new Date(str),
                mnth = ("0" + (date.getMonth() + 1)).slice(-2),
                day = ("0" + date.getDate()).slice(-2);
            return [date.getFullYear(), mnth, day].join("-");
        }
        var myTable;
        myTable = $("#Campaigns").DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [[10, 20, 30, 40, 50, -1], [10, 20, 30, 40, 50, "All"]],
        });
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url: "/Campaign/GetAllCampaign",
            async: false,
            success: function (data) {
                console.log(data);
                for (var i = 0; i < data.length; i++) {
                    $('#Campaigns').dataTable().fnAddData([
                        data[i].Name,
                        data[i].Description,
                        data[i].OwnerShip,
                        convert(parseInt(data[i].CreatedDate.substr(6))),
                        "<a class='fa fa-trash-o color_div' href='/Campaign/EditCampaign/" + data[i].Id + "'>&nbsp; Edit</a>",
                        "<a class='fa fa-trash-o color_div' id=btn_Delcampaign data-id=" + data[i].Id + ">&nbsp; Delete</a>"
                    ]);
                }
            }
        });
    </script>
    <script>
        $(function () {
            $("#Campaigns").on("click", "#btn_Delcampaign", function () {
                alert("entred");
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                alert(id);
                $('#deleteModal').modal('show');
                $('#btnYes').click(function () {
                    alert("Hi");
                //var options = { "backdrop": "static", keyboard: true };
                $.ajax({
                    type: "Get",
                    url: '/Campaign/DeleteCampaign',
                    contentType: "application/json; charset=utf-8",
                    data: { "id": id },
                    datatype: "json",
                    success: function (data) {
                        alert(data);
                        window.location.href = "/Campaign/Index";
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }   
                    });
                });
                $('#btnNo').click(function () {
                    $.ajax({
                        type: "POST",
                        url: '/Campaign/Index',
                        // data: "id=" + selectedId,
                        datatype: "json",
                        success: function () {
                        },
                    });
                });
            });
        });
    </script>
} 