Key2Home/Controllers/SuperAdminController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Key2Home.Models;
using Key2Home.SuperAdminViewModel;
using Key2Home.ViewModel;

namespace Key2Home.Controllers
{
    public class SuperAdminController : Controller
    {
        KeyToHomeEntities db = new KeyToHomeEntities();
        // GET: SuperAdmin
        public ActionResult Index()
        {
            return View();
        }

        #region SuperAdmin
        // GET: SuperAdmin
        /// <summary>
        /// Active Customer for show the view
        /// </summary>
        /// <returns></returns>
        public ActionResult ActiveCustomer()
        {

            return View("ActiveCustomerSuperAdmin");
        }
        /// <summary>
        /// Get All the Active Customer List
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetActiveCustomerList()
        {
            try
            {
                using (var _context = new KeyToHomeEntities())
                {
                    int adminId = Convert.ToInt32(Session["AdminId"].ToString());
                    var obj = _context.admins.Where(p => p.AdminID != adminId  && p.IsDeleted != true).OrderByDescending(c => c.CreateOn).ToList();
                    if (obj.Count() > 0)
                    {
                        ViewBag.UserLlist = "true";

                    }
                    return Json(obj, JsonRequestBehavior.AllowGet);

                }

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }


        /// <summary>
        /// Agent Detail SuperAdmin for single individual
        /// </summary>
        /// <param name="AdminID"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult AgentDetailSuperAdmin(int? id)
        {
            try
            {
                AppListViewModel result = new AppListViewModel();
                var obj = db.admins.Find(id);
                if (obj != null)
                {
                    result.AdminID = obj.AdminID;
                    result.AdminName = obj.AdminName;
                    result.AdminEmail = obj.AdminEmail;
                    result.Phone = obj.Phone;
                    result.Plan = obj.PLans;
                    var appObj = db.Applists.FirstOrDefault();
                    if (appObj != null)
                    {
                        result.AppLogo = appObj.AppLogo;
                        result.AppName = appObj.AppName;
                        result.AgentName = appObj.AgentName;
                        result.AppShortDiscription = appObj.AppShortDiscription;
                        result.AppFullDiscription = appObj.AppFullDiscription;
                        result.ThemeColorCode = appObj.ThemeColorCode;
                    }
                }
                return View("AgentDetailSuperAdmin", result);
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
        /// <summary>
        /// Deactivate Active Customer
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult DeactivateActiveCustomer(int id)
        {
            try
            {

                bool result = false;
                admin obj = new admin();
                obj = db.admins.Where(a => a.AdminID == id && a.IsDeleted != true).FirstOrDefault();
                if (obj != null)
                {
                    obj.IsActive = (obj.IsActive == true || obj.IsActive == null) ? false : true;
                    db.SaveChanges();
                    result = true;
                }

                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;

            }

        }

       
        /// <summary>
        /// Delete Customer for show the view
        /// </summary>
        /// <returns></returns>
        public ActionResult DeleteCustomer()
        {

            return View("DeleteCustomerSuperAdmin");
        }
        /// <summary>
        /// Get Delete Customer List for all customer 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetDeleteCustomerList()
        {
            try
            {
                using (var _context = new KeyToHomeEntities())
                {
                    int adminId = Convert.ToInt32(Session["AdminId"].ToString());
                    var obj = _context.admins.Where(c => c.AdminID != adminId && c.IsDeleted != true).OrderByDescending(o => o.CreateOn).ToList();
                    if (obj.Count() > 0)
                    {
                        ViewBag.UserLlist = "true";
                    }
                    return Json(obj, JsonRequestBehavior.AllowGet);

                }

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        /// <summary>
        /// Get Deletet Agent Detail by id
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetDeletetAgentDetail(int? Id)
        {
            try
            {
                admin obj = new admin();
                obj = db.admins.Find(Id);
                return Json(obj, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;

            }

        }
        /// <summary>
        /// Delete Agent Detail Super Admin for view detail
        /// </summary>
        /// <param name="AdminID"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult DeleteAgentDetailSuperAdmin(int? id)
        {
            try
            {
                AppListViewModel result = new AppListViewModel();
                var obj = db.admins.Find(id);
                if (obj != null)
                {
                    result.AdminID = obj.AdminID;
                    result.AdminName = obj.AdminName;
                    result.AdminEmail = obj.AdminEmail;
                    result.Phone = obj.Phone;
                    result.Plan = obj.PLans;
                    var appObj = db.Applists.FirstOrDefault();
                    if (appObj != null)
                    {
                        result.AppLogo = appObj.AppLogo;
                        result.AppName = appObj.AppName;
                        result.AgentName = appObj.AgentName;
                        result.AppShortDiscription = appObj.AppShortDiscription;
                        result.AppFullDiscription = appObj.AppFullDiscription;
                        result.ThemeColorCode = appObj.ThemeColorCode;
                    }
                }
                return View("DeleteAgentDetailSuperAdmin", result);
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }
        /// <summary>
        /// Delete User by AdminID
        /// </summary>
        /// <param name="AdminID"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult DeleteUser(int id)
        {
            try
            {
                bool result = false;
                var obj = db.admins.Where(a => a.AdminID == id).FirstOrDefault();
                if (obj.AdminID > 0)
                {
                    obj.IsActive = false;
                    obj.IsDeleted = true;
                    db.SaveChanges();
                    result = true;


                }

                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;

            }

        }
        /// <summary>
        /// AppList for show view
        /// </summary>
        /// <returns></returns>
        public ActionResult AppList()
        {

            return View("AppListSuperAdmin");
        }
        /// <summary>
        /// App List Detail
        /// </summary>
        /// <returns></returns>

        [HttpGet]
        public ActionResult AppListDetail()
        {
            try
            {
                using (var _context = new KeyToHomeEntities())
                {
                    var obj = _context.Applists.Where(c => c.isActive != false && c.isDeleted != true).OrderByDescending(o => o.Id).ToList();
                    if (obj.Count() > 0)
                    {
                        ViewBag.UserLlist = "true";
                    }
                    return Json(obj, JsonRequestBehavior.AllowGet);

                }

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        /// <summary>
        /// DeleteAppList
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult DeleteAppList(int id)
        {
            try
            {
                bool result = false;
                using (var _context = new KeyToHomeEntities())
                {
                    var obj = _context.Applists.Where(c => c.Id == id).FirstOrDefault();

                    if (obj.Id > 0)
                    {
                        obj.isActive = false;
                        obj.isDeleted = true;
                        _context.SaveChanges();
                        result = true;
                    }
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        public ActionResult ChangePassword()
        {

            return View("ChangePasswordSuperAdmin");

Key2Home/Views/SuperAdmin/ActiveCustomerSuperAdmin.cshtml
@model Key2Home.Models.admin
@{
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}
<style>
    .color_div {
        color: #269e56 !important;
    }
</style>
<!-- MAIN -->

<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            <div class="header_heading">
                <h3 class="page-title main_heading">Agent List</h3>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-bordered admin_table" id="Users">
                    <thead>
                        <tr>
                            <th>Admin Name</th>
                            @*<th>Last Name</th>*@
                            <th>Admin Email </th>
                            <th>Phone</th>
                            <th>Plans</th>
                            <th>View Detail</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
<div class="clearfix"></div>



<div id='myModal' class='modal'>
    <div class="modal-dialog" style="width: 1000px;height: 108px;position: absolute;top: 20%;left: 50%;margin-top: -48px; margin-left: -239px;padding: 15px;">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>


<script>

    $(document).ready(function () {

        myTable();
    });
    function myTable() {
        $("#Users").DataTable({
            "destroy":true,
            "pagingType": "full_numbers",
            "lengthMenu": [[10, 20, 30, 40, 50, -1], [10, 20, 30, 40, 50, "All"]],
        });
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url: "/SuperAdmin/GetActiveCustomerList",
            async: false,
            success: function (data) {
                $('#Users').dataTable().fnClearTable();
                for (var i = 0; i < data.length; i++) {
                    if (data[i].IsActive !== false) {
                        var Name;
                        Name = "Activate";
                        var Names;
                        Names = "fa fa-check-circle-o btn btn-success btn btn-sm";
                    }
                    else{
                        var Name;
                        Name = "Deactivate";
                        var Names;
                        Names = "fa fa-times btn btn-danger btn btn-sm";

                    }
                    $('#Users').dataTable().fnAddData([
                        data[i].AdminName,
                        data[i].AdminEmail,
                        data[i].Phone,
                        data[i].PLans,

                        "<a class='btn btn-primary btn_hover_shadow btn-sm' id=agent_detail data-id= " + data[i].AdminID + " href=/SuperAdmin/AgentDetailSuperAdmin/" + data[i].AdminID + ">&nbsp;View Details</a>",
                        '<a style="margin: 0px; text - align: center" class="btn' + Names + '" onclick="Deactivate(' + data[i].AdminID + ', ' + data[i].IsActive+')">&nbsp;'+ Name + '</a>'

                    ]);
                }
            }
        });
    }
   
        $(function () {

            @*$("#Users").on("click", "#agent_detail", function () {
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                var options = { "backdrop": "static", keyboard: true };
                $.ajax({
                    type: "GET",
                    url: '/SuperAdmin/AgentDetailSuperAdmin',
                    contentType: "application/json; charset=utf-8",
                    data: { "AdminID": id },
                    datatype: "json",
                    success: function (data) {
                        $('#myModalContent').html(data);
                        var id = data.AdminID;
                      //  window.location = '@Url.Action("AgentDetailSuperAdmin", "SuperAdmin", new { AdminID = "CC"})'.replace("CC", id);

                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });*@
            $("#closbtn").click(function () {
                $('#myModal').modal('hide');
            });
        });


        /* Delete the  user  */
        function Deactivate(data, status) {
            var mydata = data;
            var message = '';
            var title = '';
            if (status !== false) {
                message = "deactivate";
                title = 'Deactivated';
            }
            else {
                message = "activate";
                title = "Activated";
            }
            swal({
                title: "Are you sure?",
                text: "You want to "+message+" this user!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, " + message+ " it!",
                closeOnConfirm: true
            },
                function (result) {
                    if (result == true) {
                        DeleteUserRequest(mydata,title);
                    }

                });
        }

        /* Delete User Call Function */
        function DeleteUserRequest(data, title) {
            var id = +data;
            $.ajax({
                url: '/SuperAdmin/DeactivateActiveCustomer/' + id,
                type: "Get",
                dataType: "json",
                contentType: "application/json; charset=utf-8;",
                success: function (data) {
                    if (data === true) {
                        swal(title, "User " + title + " successfully.", "success");
                        myTable();
                    }
                    else {
                        swal("Error!", data, "error");
                    }
                },
                failure: function (response) {
                    alert(response);
                }
            });
        }
</script>

Key2Home/Views/SuperAdmin/AgentDetailSuperAdmin.cshtml
@model Key2Home.SuperAdminViewModel.AppListViewModel
 
@{
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}
<style>
    .color_div {
        color: #269e56 !important;
    }
    .back_clr {
        color: #fff;
    }

        .back_clr :hover {
            color:#ee5e11;
        }
</style>
<!-- MAIN -->
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            <div class="header_heading">
                <h3 class="page-title main_heading">Agent Detail</h3>
                <button style="margin:0px;" id="Back_Btn" class="btn btn-orange pull-right">
                    <div class="effect"></div>
                    <span><i class="lnr lnr-arrow-left"><a href="@Url.Action("ActiveCustomer", "SuperAdmin")" class="back_clr">Back</a></i></span>
                    @*<span><i class="lnr lnr-arrow-left"></i>Back</span>*@
                </button>
            </div>
            <div class="panel panel-profile">
                <div class="clearfix">
                    <!-- LEFT COLUMN -->
                    <div class="profile-left">
                        <!-- PROFILE HEADER -->
                        <div class="profile-header">
                            <div class="overlay"></div>
                            <div class="profile-main">
                                <img src="~/Assests/SuperAdmin/img/profile_img.jpg" class="img-circle" alt="pic">

                            </div>

                        </div>
                        <!-- END PROFILE HEADER -->
                        <!-- PROFILE DETAIL -->
                        <div class="profile-detail" id="agent_detail">
                            <div class="profile-info">
                                <h4 class="heading">Basic Info</h4>
                                @if (Model != null)
                                {
                                    <ul class="list-unstyled list-justify">
                                        <li>Admin Name <span>@Model.AdminName</span></li>
                                        <li>Admin Email <span>@Model.AdminEmail</span></li>
                                        <li>Phone<span>@Model.Phone</span></li>
                                        <li>Plan <span>@Model.Plan</span></li>

                                    </ul>
                                }
                                @* @Html.Partial("_GetAgentDetailPartial")*@

                            </div>
                            <div class="text-center"><a href="@Url.Action("AgentDetailSuperAdmin", "SuperAdmin",new {@Model.AdminID})" class="btn btn-primary">Go To User Detail</a></div>
                        </div>
                        <!-- END PROFILE DETAIL -->
                    </div>
                    <!-- END LEFT COLUMN -->
                    <!-- RIGHT COLUMN -->
                    <div class="profile-right">

                        <!-- END AWARDS -->
                        <!-- TABBED CONTENT -->
                        <div class="custom-tabs-line tabs-line-bottom left-aligned">
                            <ul class="nav" role="tablist">
                                <li class="active"><a href="#tab-bottom-left1" role="tab" data-toggle="tab">App Info</a></li>

                            </ul>
                        </div>
                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="tab-bottom-left1">
                                <ul class="list-unstyled activity-timeline">
                                    <li>
                                        <i class="fa fa-check activity-icon"></i>
                                        <p>App Name<span class="timestamp">@Model.AppName</span></p>
                                    </li>
                                    <li>
                                        <i class="fa fa-check activity-icon"></i>
                                        <p>Title<span class="timestamp">@Model.AgentName</span></p>
                                    </li>
                                    <li>
                                        <i class="fa fa-check activity-icon"></i>
                                        <p>Theme color Code<span class="timestamp">@Model.ThemeColorCode<span style="background-color:@Model.ThemeColorCode" class="color_code"></span></span></p>
                                    </li>

                                </ul>

                                <div class="profile-info">
                                    <h4 class="heading">App Short Discription</h4>
                                    <p>
                                       @Model.AppShortDiscription
                                    </p>
                                </div>
                                <div class="profile-info" style="margin-top:30px;">
                                    <h4 class="heading">App Full Discription</h4>
                                    <p>
                                        @Model.AppFullDiscription
                                    </p>
                                </div>
                                <div class="profile-info" style="margin-top:30px;">
                                    <h4 class="heading">App Logo</h4>
                                    <p><img src="~/Assests/SuperAdmin/img/big-logo.png" alt="company logo" height="100px;" /></p>

                                </div>


                            </div>

                        </div>
                        <!-- END TABBED CONTENT -->
                    </div>
                    <!-- END RIGHT COLUMN -->
                </div>
            </div>
        </div>
    </div>

    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->

<div class="clearfix"></div>




@section scripts
    {

    <script type="text/javascript">
        $('#delete').click(function () {
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover this data!",
                type: "warning",
                showCancelButton: true,
                confirmButtonText: "Yes, delete it!",
                cancelButtonText: "cancel",
                closeOnConfirm: false,
                closeOnCancel: false
            }, function (isConfirm) {
                if (isConfirm) {
                    swal("Deleted!", "Your record has been deleted.", "success");
                } else {
                    swal("Cancelled", "Your record is safe :)", "error");
                }
            });
        });
    </script>
    <script type="text/javascript">
        //$('#Back_Btn').click(function () {
        //    window.location.href = 'ActiveCustomerSuperAdmin.html';
        //})
    </script>
    <script type="text/javascript">

        $(document).ready(function () {
            // executes when HTML-Document is loaded and DOM is ready
            console.log("document is ready");

            $('.lightbox').each(function (index) {
                $(this).click(function () {
                    var imgSrc = $(this).children("img").attr("data-img");

                    $('body').append('<div id="lightbox-modal" class="modal fade" tabindex="-1" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button></div><div class="modal-body"><img src="' + imgSrc + '" class="img-responsive"></div></div></div></div>');
                    $('#lightbox-modal').modal({ show: true });

                    $('#lightbox-modal').on('hidden.bs.modal', function (e) {
                        $(this).remove();
                    })
                    return false;
                });
            });


            // document ready
        });



    </script>


}

Key2Home/Views/SuperAdmin/DeleteCustomerSuperAdmin.cshtml
@model Key2Home.SuperAdminViewModel.AppListViewModel
@{
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}
<style>
    .color_div {
        color: #269e56 !important;
    }
</style>
<!-- MAIN -->
<!-- MAIN -->

<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            <div class="header_heading">
                <h3 class="page-title main_heading">Delete Customer</h3>
                <!--<button style="margin:0px;" id="create_Btn" class="btn btn-orange pull-right"><div class="effect"></div> <span>Create Agent</span></button>-->
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-bordered admin_table" id="Users">
                    <thead>
                        <tr>
                            <th>Admin Name</th>
                            <th>Admin Email </th>
                            <th>Phone</th>
                            <th>Plans</th>
                            <th>View Detail</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @*<tr>
                                <td>Swarn </td>
                                <td>Singh</td>
                                <td>swarnsingh@gmail.com</td>
                                <td>8585994422</td>
                                <td>Basic Plan <span class="text-danger">$39</span></td>
                                <td><button id="agent_detail" class="btn btn-primary btn_hover_shadow btn-sm">View Detail</button></td>


                                <td><button id="delete" class="btn btn-danger btn_hover_shadow btn-sm">Delete</button></td>
                            </tr>
                            <tr>
                                <td>Swarn </td>
                                <td>Singh</td>
                                <td>swarnsingh@gmail.com</td>
                                <td>8585994422</td>
                                <td>Basic Plan <span class="text-danger">$39</span></td>
                                <td><button class="btn btn-primary btn_hover_shadow btn-sm">View Detail</button></td>


                                <td><button class="btn btn-danger btn_hover_shadow btn-sm">Delete</button></td>
                            </tr>
                            <tr>
                                <td>Swarn </td>
                                <td>Singh</td>
                                <td>swarnsingh@gmail.com</td>
                                <td>8585994422</td>
                                <td>Basic Plan <span class="text-danger">$39</span></td>
                                <td><button class="btn btn-primary btn_hover_shadow btn-sm">View Detail</button></td>
                                <td><button class="btn btn-danger btn_hover_shadow btn-sm">Delete</button></td>
                            </tr>*@
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
<!-- END MAIN -->
<div class="clearfix"></div>



<div id='myModal' class='modal'>
    <div class="modal-dialog" style="width: 500px;height: 108px;position: absolute;top: 20%;left: 50%;margin-top: -48px; margin-left: -239px;padding: 15px;">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>

</div>



<script>

        function myTable() {
        $("#Users").DataTable({
            "destroy": true,
            "pagingType": "full_numbers",
            "lengthMenu": [[10, 20, 30, 40, 50, -1], [10, 20, 30, 40, 50, "All"]],
        });
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url: "/SuperAdmin/GetDeleteCustomerList",
            async: false,
            success: function (data) {
                $('#Users').dataTable().fnClearTable();
                for (var i = 0; i < data.length; i++) {
                    $('#Users').dataTable().fnAddData([
                        data[i].AdminName,
                        data[i].AdminEmail,
                        data[i].Phone,
                        data[i].PLans,

                        "<a class='btn btn-primary btn_hover_shadow btn-sm' id=delagent_detail data-id= " + data[i].AdminID + " href=/SuperAdmin/DeleteAgentDetailSuperAdmin/" + data[i].AdminID + ">&nbsp;View Details</a>",
                        '<a style="margin: 0px; text - align: center" class="btn btn-danger btn_hover_shadow btn-sm" onclick="DeleteUser(' + data[i].AdminID + ')">&nbsp;Delete</a>'

                    ]);

                  
                }
            }
    
            });
        }

        $(function () {

            @*$("#Users").on("click", "#delagent_detail", function () {
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                var options = { "backdrop": "static", keyboard: true };
                $.ajax({
                    type: "GET",
                    url: '/SuperAdmin/GetDeletetAgentDetail',
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        $('#myModalContent').html(data);
                        var id = data.AdminID;
                       window.location = '@Url.Action("DeleteAgentDetailSuperAdmin", "SuperAdmin", new { AdminID = "CC"})'.replace("CC", id);

                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });*@
            });
            $("#closbtn").click(function () {
                $('#myModal').modal('hide');
            });
        

        /* Delete the  user  */
        function DeleteUser(data) {
            var mydata = data;
            swal({
                title: "Are you sure?",
                text: "You want to delete this category!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: true
            },
                function (result) {
                    if (result == true) {
                        DeleteUserRequest(mydata);
                    }

                });
        }

        /* Delete User Call Function */
        function DeleteUserRequest(data) {
           
            var id = +data;
            $.ajax({
                url: '/SuperAdmin/DeleteUser/' + id,
                type: "Get",
                dataType: "json",
                contentType: "application/json; charset=utf-8;",
                success: function (data) {
                      if (data === true) {
                        swal("Deleted!", "Customer deleted successfully.", "success");
                          myTable();
                    }
                    else {
                        swal("Error!", data, "error");
                    }
                },
                failure: function (response) {
                    alert(response);
                }
            });
        }

        $(document).ready(function () {

            myTable();
        });
</script>